### ISSUE TITLE
TestApp uses NibClassBuilder, dropped in XCode 4+

### ISSUE THREAD

**Issue by adrientetar** [typesupply/defconAppKit#8]

**Comment by miguelsousa** [comment]
@typemytype @typesupply @adrientetar any pointers on how to fix this?

**Comment by typesupply** [comment]
The line just needed to be deleted. I just pushed a change that lets the app launch. Beyond launching, um, I don't know if it still works. I haven't touched this in years.

**Comment by miguelsousa** [comment]
It's not that simple. I have recent versions of `setuptools` and `pyobjc`. The app compiles but crashes on launch, because [`NibClassBuilder` is still referenced](https://github.com/typesupply/defconAppKit/blob/master/TestApp/DefconAppKitTest.py#L2). Removing it allows the app to launch, but then it crashes later, upon opening a UFO. Traceback below. Doesn't seem like it has anything to do with nib loading though. I'll try to look into it.
```python
Traceback (most recent call last):
  File "/TestApp/dist/DefconAppKitTest.app/Contents/Resources/DefconAppKitTest.py", line 35, in readFromFile_ofType_
    window = self.vanillaWindowController = DefconAppKitTestDocumentWindow(font)
  File "/TestApp/dist/DefconAppKitTest.app/Contents/Resources/DefconAppKitTest.py", line 82, in __init__
    deleteCallback=self.collectionViewDeleteCallback, selfDropSettings=selfDropSettings, selfApplicationDropSettings=dropSettings)
  File "defconAppKit/controls/glyphCollectionView.pyc", line 143, in __init__
  File "defconAppKit/controls/glyphCellView.pyc", line 90, in initWithFrame_cellRepresentationName_detailWindowClass_
AttributeError: 'super' object has no attribute 'initWithFrame_'
```

**Comment by typesupply** [comment]
Try changing that line to:

```python
self = super(DefconAppKitGlyphCellNSView, self).alloc().initWithFrame_(frame)
```

There was a time ages ago when PyObjC was kinda flaky about the `alloc` call. It could have been the last time I worked on this branch.

**Comment by miguelsousa** [comment]
Replaced line 90 and now the error is:
```python
AttributeError: 'super' object has no attribute 'alloc'
```

**Comment by typesupply** [comment]
Good times!

(And people wonder why the next MetricsMachine isn't finished.)

**Comment by miguelsousa** [comment]
This works:
```python
self = DefconAppKitGlyphCellNSView.alloc().initWithFrame_(frame)
```
The app compiles and launches, but then it freezes when switching to the **GlyphCollectionView** or **GlyphView** tabs. The traceback is now this:
```python
Traceback (most recent call last):
  File "defconAppKit/controls/glyphCellView.pyc", line 332, in drawRect_
  File "defcon/objects/base.pyc", line 338, in getRepresentation
TypeError: GlyphCellFactory() takes at least 4 arguments (5 given)
```
I'll keep digging and report back if I get stuck.

**Comment by benkiel** [comment]
@miguelsousa Looking at this, I think the root cause here may be that you're using the UFO3 branch of defcon, where this was likely written for the master branch — it looks (quick reading, could be missing something) that representations are slightly different in the UFO3 branch, which may be the reason here.

**Comment by miguelsousa** [comment]
@benkiel you're right, this last error is caused by that. Thanks!
